# Generated by Django 4.1.4 on 2023-04-17 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storestatus',
            name='date_utc',
        ),
        migrations.RemoveField(
            model_name='storestatus',
            name='time_utc',
        ),
        migrations.AddField(
            model_name='storestatus',
            name='datetime_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='datetime_temp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='datetime_utc',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storetimezone',
            name='utcoffset',
            field=models.IntegerField(default=-500),
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='storeid',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['storeid'], name='tasks_busin_storeid_1d9cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['storeid'], name='tasks_store_storeid_7f4410_idx'),
        ),
        migrations.AddIndex(
            model_name='storetimezone',
            index=models.Index(fields=['storeid'], name='tasks_store_storeid_a30b63_idx'),
        ),
    ]
