# Generated by Django 4.1.4 on 2023-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.CharField(max_length=150)),
                ('dayofweek', models.IntegerField(null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.CharField(max_length=150)),
                ('datetime_utc', models.DateTimeField()),
                ('datetime_local', models.DateTimeField(auto_now=True)),
                ('datetime_temp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.CharField(max_length=150, unique=True)),
                ('timezone', models.CharField(max_length=150)),
                ('utcoffset', models.IntegerField(default=-500)),
            ],
        ),
        migrations.AddIndex(
            model_name='storetimezone',
            index=models.Index(fields=['storeid'], name='createmodel_storeid_d5caa7_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['storeid'], name='createmodel_storeid_0f91db_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['storeid'], name='createmodel_storeid_e23081_idx'),
        ),
    ]
