# Generated by Django 4.1.4 on 2023-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0005_remove_storestatus_date_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetimezone',
            name='utcoffset',
            field=models.IntegerField(default=-500),
        ),
    ]
