# Generated by Django 4.1.4 on 2023-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0006_storetimezone_utcoffset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetimezone',
            name='storeid',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
