# Generated by Django 4.1.4 on 2023-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0007_alter_storetimezone_storeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestatus',
            name='datetime_local',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
