# Generated by Django 4.1.4 on 2023-04-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0008_storestatus_datetime_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestatus',
            name='datetime_temp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
