# Generated by Django 4.1.4 on 2023-04-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0009_storestatus_datetime_temp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['storeid'], name='createmodel_storeid_e23081_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['storeid'], name='createmodel_storeid_0f91db_idx'),
        ),
        migrations.AddIndex(
            model_name='storetimezone',
            index=models.Index(fields=['storeid'], name='createmodel_storeid_d5caa7_idx'),
        ),
    ]
